### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by yjeanrenaud**
literal translation might lead to confusion

### CODE REVIEW

**Comment by yjeanrenaud** [comment]
so just close? -_-

**Comment by AbandonedCart** [comment]
wdym?

**Comment by yjeanrenaud** [comment]
never mind, I was in the wrong window. Thank you for accepting the pr.
the Dimensions figurines do not run under a localised name in Germany (nor in France, afaik) I will check some more of the translations when I got time.

**Comment by AbandonedCart** [comment]
I couldn't find a trademark for Dimensions, so it should be acceptable to treat it as a proper name.

**Pull request closed without merging**
