### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by CTCaer**

### CODE REVIEW

**Comment by CTCaer** [comment]
Refined the shadows a little bit

**Comment by Bombastisch** [comment]
I like it :D  I can't really see it on mobile rn, but it seems a bit small. Could just be my view here in this app, but could you maybe if it is the case, make the logo a bit bigger so it's better readable?

**Comment by CTCaer** [comment]
Nice, I'll change it.

I'll post it probably tomorrow.

**Comment by CTCaer** [comment]
Made the circles bigger and slightly made some distance between them.
Bigger NFC tag logo.
Slightly upped the font size for TagMo to better match the bigger logo.

**Comment by Bombastisch** [comment]
Awesome! :D @HiddenRambler what do you think?

**Comment by CTCaer** [comment]
BTW, I want to state that this weekend I have a lot of free time.
So a decision should not be rushed.

Additionally, if you want to check how it looks like in your device without recompiling it, just download the icon for your dpi and change manually choose it as an app icon, if your launcher supports this function.

**Comment by HiddenRambler** [comment]
The icon looks great. I'll merge the request soon as I can (hopefully on the weekend.)

Could you pehaps include a large png of the logo (without the outer enclosing circle) so it could be used in somewhere else in the application if needed? It could go into a folder called assets in the root of the repository. (or create an issue an attach it and i'll drop it in).

**Comment by Bombastisch** [comment]
@CTCaer Just a small thing but could you maybe move the dots further apart from each other? Just a very little bit, because I think in it's current state it looks kinda squeezed together)

**Comment by CTCaer** [comment]
@HiddenRambler 
I will

@Bombastisch 
There are as far away as possible without risking losing symmetry and touching TagMo.
I can make TagMo smaller and move the dots, but again, with the latest change it has way better readability than before.
Another way is to replace NFC tag logo with tagmo.

**Comment by Bombastisch** [comment]
A logo in the logo? xD I like it how it is, was just curious if it was possible. I like it, better than the "old" logo. This fits much better.

**Comment by CTCaer** [comment]
He he :D

I've added the most needed assets as requested by @HiddenRambler in this PR. 
In the future anyone can work based on these. 
Lastly, I've also took the liberty to add notification icons based on the new icon.

**Comment by Bombastisch** [comment]
Yes now we can finally remind our users to create new tags! ^^ we will for sure find a use for it. LGTM

**Comment by HiddenRambler** [comment]
I've merged the commit. The logo looks great :) Thank you.

**Pull request merged**
