### PR TITLE
Polish Amiibo Image Views

### PR DESCRIPTION
**Pull request by North101**
## Done

- Adds different views for amiibo.
  1. Simple (just text)
  2. Compact (left small image + text)
  3. Large (top large image + text)
- Updated icons

## Planned:
- Click image for preview/save
- Disable fetching images when not on wifi

screenshot_20170828-165425
screenshot_20170828-165412
screenshot_20170828-165420
screenshot_20170828-165446
screenshot_20170828-165459
screenshot_20170828-165635
screenshot_20170828-165459

### CODE REVIEW

**Comment by HiddenRambler** [comment]
This is awesome. I'm tempted to push out a release just for this.

**Comment by North101** [comment]
Noooo... It was still in progress! (It was stable to merge though)

**Comment by HiddenRambler** [comment]
Just noticed that the editor was disabled

**Comment by HiddenRambler** [comment]
I'll keep it. it looks stable enough. We'll do a release after the editor buttons are sorted.

**Comment by North101** [comment]
@HiddenRambler that should be the only thing not working at the moment. I've made some minor changes to the compact view since as well

**Comment by North101** [comment]
@HiddenRambler I've merged the image preview and network options for image download

**Pull request merged**
