### PR TITLE
Add image preview on browser and selected amiibo using amiiboapi.com …

### PR DESCRIPTION
**Pull request by H3llK33p3r**
Hi to have a better user view I have added the amiibo image icon present on the database if this one exists. 

When browsing or on main menu the image is displayed using picasso api to get/manage/cache the image.

### CODE REVIEW

**Comment by Bombastisch** [comment]
Can you show us a image of how it looks?  I am very interested in this PR!

**Comment by H3llK33p3r** [comment]
@Bombastisch sure, here an example on the browser view:
screenshot_20170822-204456. 

Images displayed are the ones in the amiiboapi.com site and you have an example of the internal android icon used when there is no image to display. Same view is used on the main_activity.

**Comment by Bombastisch** [comment]
I hope the devs will merge it soon! I really like this. :D

**Comment by Bombastisch** [comment]
Can you click on the images? It would be cool to download the images via the app, so you can  easily print them and glue them onto your NTag215s

**Comment by HiddenRambler** [comment]
Thanks @H3llK33p3r it looks good. Appreciate the contribution.

But please avoid making whitespace changes along with feature changes.

**Comment by H3llK33p3r** [comment]
@HiddenRambler I will try to remember that if I contribute another time but can be useful to reformat all the code with the default android studio formatter to avoid this!

@Bombastisch it can be easily added but not sure that is an interested feature. By googling subject you can find pdf with many amiibos already resized to be printed and glued on ntag215 stickers.

**Pull request merged**
