### PR TITLE
Project Abandoned - See Details

### PR DESCRIPTION
**Pull request by AbandonedCart**
https://github.com/8BitDream/TagMo has continued this project.

Per issue https://github.com/HiddenRamblings/TagMo/issues/248, no further contributions will be made directly to this repository. This PR will remain to document progress, but may not be monitored for discussion.

Please feel free to direct pull requests to https://github.com/8BitDream/TagMo/pulls to have them reviewed.

Test versions are built and published through Github Actions at https://github.com/8BitDream/TagMo/actions

### CODE REVIEW

**Comment by Rupan** [comment]
As you mention in the description, this change isn't really reviewable in its current form.  I really wish Github had something like Phabricator's stacked commits, but sadly the best currently available is stacked PRs:

https://blog.logrocket.com/using-stacked-pull-requests-in-github/

**Comment by AbandonedCart** [comment]
As stated in the description, this is provided for the end user. No review is requested.

**Comment by AbandonedCart** [comment]
> This application falls under the exemption for permitted uses of the all files access permission -> Document management apps
> 
> "Apps that must locate, access, and edit compatible file types outside of its app-specific or shared storage"
> 
> https://support.google.com/googleplay/android-developer/answer/10467955

 - 6ea41992157db8a2b83342bc1c5920d0f06e65fc

**Comment by Buzbee** [comment]
Any chance you can reduce the minSdkVersion 21 back down to 14? I need 16. I have newer phones but not with nfc.

**Comment by AbandonedCart** [comment]
https://developer.android.com/reference/java/net/HttpURLConnection#secure-communication-with-https
https://developer.android.com/reference/javax/net/ssl/HttpsURLConnection

An HttpsURLConnection extends HttpURLConnection for performing specialized https tasks associated with connecting to a secure server. No such tasks are performed when reading a json file without any authentication, so HttpsURLConnection is unnecessary.

Please see #246 for information about your error, which appears to be in retrieving the response code.

**Comment by AbandonedCart** [comment]
Legacy compatibility is strictly experimental. I don't have a device to test, so it is being included until such time as it's found to not work or get in the way of the primary purpose of this PR. As is, the code will compile and it does not break functionality on newer devices.

**Comment by AbandonedCart** [comment]
While converting hardcoded strings to resources may not be much of an optimization in itself, the process is allowing multiple instances of the same text to be combined into a single resource. This should also make it significantly easier to allow for translation in the future.

**Comment by AbandonedCart** [comment]
This should be squashed down to at least somewhat individual features now.

**Pull request closed without merging**
