### PR TITLE
Option to show missing amiibos in amiibo browser (they cant be selected).

### PR DESCRIPTION
**Pull request by North101**
Option to show missing amiibos in amiibo browser (they cant be selected).

Only enabled when recursive files mode is enabled.

### CODE REVIEW

**Comment by North101** [comment]
screenshot_20171125-224516

**Comment by Bombastisch** [comment]
I think "not found" could lead to a lot of confusion.

A lot of people might start TagMo for the first time without any .bins at all so "not found" might lead to the conclusion that the app doesn't work properly.
-> Many issue threads on github

Maybe a longer text like "binary file does not exist (in this directory)" would be more self explaining.

Thanks for the PR, missed you here on GitHub ;)

**Comment by North101** [comment]
@Bombastisch Its not enabled by default. Maybe "No files for this Amiibo found"?

Thanks, been busy with work and other projects.

**Comment by North101** [comment]
screenshot_20171125-231705

**Comment by Bombastisch** [comment]
Yes I like that! ;)

(I really don't like to be picky, but was it on purpose to write "Found" with a capital letter or just a typo?)

-small offtopic, because I didn't quite understand. What does "find files recursively" mean and what does it change?

Really glad you are back :)

**Comment by North101** [comment]
> (I really don't like to be picky, but was it on purpose to write "Found" with a capital letter or just a typo?)
It was a typo, already changed. It was because it was "Not Found" previously, I didn't retype the "Found"

> -small offtopic, because I didn't quite understand. What does "find files recursively" mean and what does it change?
It means that it won't find amiibo files in just the current folder but also any subfolders and sub sub folders etc
Theres probably a better name for it. Maybe Deep folder scan?

**Comment by Bombastisch** [comment]
> It was a typo, already changed. It was because it was "Not Found" previously, I didn't retype the "Found"

Alright ;)

> It means that it won't find amiibo files in just the current folder but also any subfolders and sub sub folders etc
Theres probably a better name for it. Maybe Deep folder scan?

Okay, thanks!

Maybe just "scan subfolders" would be the best short description

**Comment by North101** [comment]
screenshot_20171125-234555

**Comment by Bombastisch** [comment]
LGTM ;)

**Comment by Bombastisch** [comment]
Wait

**Comment by Bombastisch** [comment]
"Scan subfolders" as category doesn't really fit to " show  missing amiibos"

**Comment by Bombastisch** [comment]
Maybe you could leave out that _category name_  and just make "scan subfolders" the option name itself and leave the "enable" option out because it seems a bit unnecessary tbh.

- sorry for thr multiple messages, enter on the phone sent the message instead of new line or something.

Apart from that LGTM

**Comment by North101** [comment]
@Bombastisch I originally had them separate but it doesn't make sense to me to have "Show Missing Amiibos" and not have "Scan Subfolders". There may be a case where someone would like it so i've separated them again

**Comment by Bombastisch** [comment]
Maybe my text was a bad written, but I actually just meant a design change like this: 
tgamos

I thought like in your image, that _Show missing Amiibos_ just didn't fit to the "headline" of this menu

**Comment by North101** [comment]
It was required because it was a submenu and thats what the submenu was called. I promoted it to the same level as filter/sort/change view etc

**Comment by Bombastisch** [comment]
So maybe rename the submenue to "settings" and then change the setting name itself to "Scan subfolders" instead of "enable".

I am sorry if this sounds rude, because I'm a little bit picky. I am not trying to be. :)

But as it is now it looks a little bit unsorted to me.

**Comment by North101** [comment]
Ignore thats its on my experimental UI, but this is how that menu looks now:
screenshot_20171126-104441

**Comment by Bombastisch** [comment]
Alright, that's looking really good! :)

**Comment by AbandonedCart** [comment]
Merged to https://github.com/HiddenRamblings/TagMo/tree/experimental release

**Pull request closed without merging**
