### PR TITLE
feat: Update upload process for Flask

### PR DESCRIPTION
**Pull request by withgallantry**
Draft PR.

Version 5.1 of the Flask software compresses the byte array using base64 encoding to achieve a faster upload speed. I've added that functionality here.

I've also had a play with adding some stability to the Bluetooth requests. I did some debugging using the Flask tooling and found that the microcontroller isn't processing the commands if they are rapidly sent together.

I am not skilled at Java which is why this PR is draft. I think that adding a callback stack which is executed when the Flask signals it has processed the last command can remove the ugly timeouts I've used here.

I'm going to look at implementing something like:
https://stackoverflow.com/questions/20742628/how-to-schedule-function-calls-execution-in-a-queue

In the Javascript app on Flask.run I use callbacks to achieve this. On receiving data I check if the string is valid JSON, or if the string 'undefined' is returned (this is returned from a function ran without a return statement). I've noticed you do something similar here 
https://github.com/withgallantry/TagMo/blob/c2d596ac62685de1c502e92180842f3d3dcaa662/app/src/main/java/com/hiddenramblings/tagmo/BluetoothLeService.java#L120

Hopefully this shows the direction I was attempting. 

Edit: I forgot to mention I did some tests with Tags that I had issues with on the Flask originally, those containing hyphens etc. So I've added some escaping for that. Also shortened it form 28 to 16 when naming to save some memory.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Preventing the rapid write was addressed by `delayedWriteTagCharacteristic`, which queues the write to avoid wrapping everything individually.

https://github.com/HiddenRamblings/TagMo/commit/266b3fa96047b602bf89e305ea13ffbcc09e0160 shows how ugly it got trying to time each command individually.

**Comment by withgallantry** [comment]
> Preventing the rapid write was addressed by `delayedWriteTagCharacteristic`, which queues the write to avoid wrapping everything individually.
> 
> [266b3fa](https://github.com/HiddenRamblings/TagMo/commit/266b3fa96047b602bf89e305ea13ffbcc09e0160) shows how ugly it got trying to time each command individually.

I saw you'd implemented that. From what I can tell even though everything is being sent in an orderly queue, the execution time on the Flask has to be taken into account. It's still a bit of guesswork but I noticed more stability adding those horrendous timeouts in.

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/blob/f9f0c3fb82f1598e40d41c55f8135f88bf35b363/app/src/main/java/com/hiddenramblings/tagmo/BluetoothLeService.java#L447

is the timeout between individual portions of a command, which have to be broken down into 20 bytes because of MTU.

https://github.com/HiddenRamblings/TagMo/blob/f9f0c3fb82f1598e40d41c55f8135f88bf35b363/app/src/main/java/com/hiddenramblings/tagmo/BluetoothLeService.java#L450

is the timeout before the next full command (after the MTU breakdown completes).

50 is what you use in Javascript, but I saw a lot of people using 20 and had success with it. To account for different BLE hardware and also range (which is one thing I didn't test), it should probably be 50. 500 is half a second and the average command has at least 2 parts, putting each command at 1.5 seconds to run. The initial load will be something like 10 seconds. People start to freak out at 3.

**Comment by AbandonedCart** [comment]
Unfortunately, the callbacks are a lost cause. Javascript handles each command as a self-contained instance. Android calls it from an adapter object. Instead of getting the return from running a single command, it is an ongoing stream of returns from the command processor. The only way to get individual instances for individual callbacks would be to make individual connections and there are too many reasons that would fail to justify the benefit of not trying to break up the stream of jumbled commands.

**Comment by withgallantry** [comment]
Breaking down the commands into 20 byte portions works brilliantly. It's more the weight before sending the command itself. The 500ms works in conjunction with the queue system of sending packets. In the PR here for getList, it is waiting 500ms from when a BLE connection is established before it sends the getList command. 

So essentially it's a pause before a command is sent and the command is then split into 20 byte packets. The time between the 20 byte packets does not increase.

What I think is happening is that as soon as a command is issued, the next command is then sent, and the Flask is still processing the command it's been issued.

Correct me if I'm wrong but it works currently as:
Command -> Command1 -> Command 2.

What I've attempted to do, naively, is make it:
Command (500ms) -> Command 1 -> Command 2.

I was thinking for the callbacks we can use a queue system similar to the packets. It's what I've done in JS. I listen to the stream of data that is returned, when the stream is parseable as valid JSON or returns the string 'undefined'. I take that as a command having been executed and then run the first function on the queue. It's a pseudo callback system.

As you say though, it may be very complicated.

**Comment by AbandonedCart** [comment]
In Java, the return pretty much bleeds together as 20 byte chunks. You get part of one return and part of the next command on a line, then the rest of a command and part of the return, and so on. Android's JSON processing is not very forgiving, either. It is either a perfectly formatted JSON or a crash.

**Comment by AbandonedCart** [comment]
Take a look at https://github.com/HiddenRamblings/TagMo/commit/f69b1e84de7faa22f8501a8082d91df455b45b78 and let me know if that captured everything you were trying to add. I moved the delay for getList to where the list is displayed. This should work to add it after the command but before the next, since the get (for the active slot) is always called after that.

**Comment by withgallantry** [comment]
> Take a look at [f69b1e8](https://github.com/HiddenRamblings/TagMo/commit/f69b1e84de7faa22f8501a8082d91df455b45b78) and let me know if that captured everything you were trying to add. I moved the delay for getList to where the list is displayed. This should work to add it after the command but before the next, since the get (for the active slot) is always called after that.

Looks perfect!

**Comment by withgallantry** [comment]
Closing PR :)

**Comment by AbandonedCart** [comment]
Thanks! I started to the extra timeout on the low side, but that can always be increased separately if needed.

**Pull request closed without merging**
