### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by North101**
screenshot_20170818-181823
screenshot_20170818-181839
screenshot_20170818-181835

@HiddenRambler Thoughts?

### CODE REVIEW

**Comment by HiddenRambler** [comment]
Looks pretty nice. I'm fine with this.

**Comment by North101** [comment]
@HiddenRambler Im just using the default accent colour. It also fixes button width on smaller screen sizes.

Also, if you havent seen it already, I made these changes to the error view:
screenshot_20170818-190251
screenshot_20170818-190317

**Comment by Bombastisch** [comment]
#74 What aboubt the layout change?  You could add it aswell. Then I could close my PR

**Comment by North101** [comment]
@Bombastisch I kind of like the layout as it is. I think its more logical.

**Comment by Bombastisch** [comment]
No problem! :)  I like the colors btw! This PR looks awesome!

**Comment by North101** [comment]
@Bombastisch Its all personal preference really. Just to explain why I like it better:
All of the writing/reading (aka interacting with something physical) is on the right side while all the tag data (loading from a local file, saving to local file, viewing local file) stuff is on the left.

**Comment by HiddenRambler** [comment]
I already saw the error changes. They looked pretty good. You'r UI foo is way better than mine. :)

**Pull request merged**
