### PR TITLE
[DO NOT MERGE] Update logo

### PR DESCRIPTION
**Pull request by Bombastisch**
I've always wondered if the logo was just a quick thing or if it had anything to do with the app I didn't notice until now. Since I thought it didn't fit I made a new one.

I created this new icon with some things in mind, which I hope make sense to you.

- The logo should represent a NTAG215:
- circular form
- android nfc logo in the app typical color

I hope this idea makes sense to you and is might worth thinking about. :)

### CODE REVIEW

**Comment by HiddenRambler** [comment]
I wish we could have something which doesn't look quit so much like the generic NFC icon. I like the shadow effect though.

**Comment by Bombastisch** [comment]
Alright, I am fine with that. Maybe on the weekend I can do some more designs and then we can pick if you want. (Or would you like to keep the current logo?) If you have ideas feel free to submit them here :)

**Comment by Bombastisch** [comment]
Are the 6 short colorful lines around the official amiibo logo copyrighted? If not we could maybe implement those

**Comment by CTCaer** [comment]
As per https://trademarks.justia.com/868/10/amiibo-86810130.html
the colored rays with these exact colors are copyrighted.

But you can still do something like this:

**Comment by HiddenRambler** [comment]
I'm fine with changing the logo if we can get a nice one.

I do not want it to look like any official logo to avoid even the smallest potential for a trademark/copyright claim. 

@CTCaer  I love those logos. The 6 colour bars still look too close to the Amiibo one for my taste could we do anything about it? change it to circles or have more than 6 perhaps. I don't know I have the design sense of a rock.

**Comment by CTCaer** [comment]
They can be easily changed to circles (flat, disc or orb like).

BTW, the font used in amiibo and other nintendo logos (E-shop) is **ITC Bauhaus**, which I have a license from work. So if someone needs a text in this font please tell me (btw, I can give .ai, .svg, .eps, .psd or .png, but not the actual font files).

**Comment by Bombastisch** [comment]
@CTCaer
I am fine with closing the PR if you would like to contribute to this project with your own account. If you'd rather only help ke out with the font that's cool, too. Decision is your's and tbh you seem to be better at designing a logo ;)

**Comment by CTCaer** [comment]
@Bombastisch 
The reason I commented was to help and not to force take over your PR.

On the other hand, because I saw that you are a member of the project, you are really are OK with this.
I would love to make a PR for an app that helped having all my amiibo inside my Switch case.

Lastly, because the app supports Oreo, I will try and make an adaptive icon in the future.

**Comment by Bombastisch** [comment]
Alright I'll leqve this PR opened for now, but we will not merge it. If you propose your app icon anytime soon we will discuss and merge it. Have fun designing  :D

**Comment by HiddenRambler** [comment]
As was discussed i've merged the logo from @CTCaer in #116. So will close this PR.

**Pull request closed without merging**
