### PR TITLE
HiddenTambler/TagMo #6: Ability to edit Wolf Link heats

### PR DESCRIPTION
**Pull request by possi**
For Wolf Link the "EDIT SSB DATA"-Button is replaced by "EDIT TP DATA"-Button. (Wolf Link isn't supported by SSB).

The new Button shows a Dialog to edit:
* Shadow Cave Level-Progress
* Wolf Link-Hearts

### CODE REVIEW

**Comment by LinkofHyrule89** [comment]
Thanks for this! I hope in the future you can find a way to initialize it too so you don't need a game at all. I'm trying to find someone I know that has it but so far no luck.

**Comment by LinkofHyrule89** [comment]
Someone was saying this tool can backup/restore save data to Amiibos so maybe you can use the same tech to do that and be able to setup new Amiibo that way. https://github.com/Ordim3n/Smash-Amiibo-Cheat-Tool

**Comment by possi** [comment]
You can also use TagMo to backup and restore save data on Amiibos. Works pretty fine, as long as you don't try to write data of other Amiibos.
I've tried writing the maxed-out.bin to my Wolf link before. The result is: "Your Amiibo data is corrupt, go to system settings to reset your amiibo" (loosely translated).

What you may try is to use amiibo.vgmoz.com/hex to edit your backup.bin in comparison to the maxed-out.bin. The hearts are at Offset 238 (EE). But trying to write this to an "fresh new" backup still shows up as a "not yet done any shadow cave" within Twilight Princess HD.

**Comment by LinkofHyrule89** [comment]
Yeah my problem is there is no way for me to initialize because I don't own a Wii U or Zelda TP HD. I bought the Amiibo for the Switch version of Zelda BOTW. So hopefully I can initialize in BOTW.

**Comment by bonovox400** [comment]
Hi there. So if I have a wolf link amiibo that has NEVER been used/scanned on any nintendo device, what do I need to do in order to get 20 hearts on it?  Should I first scan it to my own wiiU's TPHD game while I play it, or keep it untouched or....?  
Will using this tool allow MY user data to be saved to the amiibo? I was following a gbatemp thread where users were passing a .bin file around of a user who had legitimately gotten 20 hearts saved to his amiibo. But I believe it put HIS user data on the bin as well.  I don't want someone elses's info on the the amiibo, just mine.  Is that possible?

**Comment by nathantschultz** [comment]
I can't get this to work. I have a save on my wolf link amiibo from the cave of shadows and I have this version of TagMo installed on my android phone. I have the retail key loaded in the app and the apps says "Unfixed key ok.", "Locked key OK." and "NFC enabled!", but when I tap scan tag it says "Tag Detected", but then it goes back to the main screen of the app with a done button and it never shows the button to "Edit TP Data". What am I doing wrong?

**Comment by possi** [comment]
@nathantschultz: Does it show the Edit SSB Data instead? Can you post a Screenshot of what TagMo shows as Amiibo-Name in top-left corner? Or send me (privately) your Dump?

**Comment by nathantschultz** [comment]
@possi This is before I scan:
screenshot_2017-02-20-12-46-54
Then I press the scan button and this shows:
screenshot_2017-02-20-12-47-29
It briefly changes the text to "Tag detected" and then shows this (with the done button):
screenshot_2017-02-20-12-47-36
I'm on an old phone, a Samsung Galaxy Nexus with Android 4.3, so that might be the problem. I use an iPhone now, but I had this lying around. Thanks for taking a look.

**Comment by possi** [comment]
Well, that seems to be a general Issue, that the NFC Data doesn't get loaded. Not related to this Pull-Request.

**Comment by nathantschultz** [comment]
@possi could you possibly make the changes mentioned in https://github.com/HiddenRambler/TagMo/issues/5#issuecomment-281559173 to your branch? I borrowed a newer phone but it crashes when you tap scan like that issue mentions. I would love to help but I've only done iOS and web development. I don't know how to build an android app and I don't have a current phone to test on. I going back and forth on deciding if I should invest time in fixing this app or just playing through twilight princess in the week and a half before breath of the wild comes out.

**Comment by azsde** [comment]
So is this PR supposed to be working ?

I don't have any amiibo, just a .bin file corresponding to wolf link, can I edit the number of hearts with this ?

**Comment by Kidel** [comment]
There are many "legit" Wolf Link .bin with maxed out hearts and stats. Safer then manual editing imo.

**Comment by LinkofHyrule89** [comment]
The problem is there is no way to initialize a new Amiibo that has never been used in a Wii U in TPHD. So you can't restore a save or edit it.

**Comment by ramenators** [comment]
I'm overwhelmingly nooby to this, can someone give me a link to a guide to set this up? I have 0 knowledge when it comes to editing apps

**Comment by North101** [comment]
@HiddenRambler I've added a check for the TP app id in PR #86. Unless someone knows how to initialize amiibo's app data for TP, should this be closed?

**Comment by Bombastisch** [comment]
@North101 Guess I can close this now, as we know how to do it, but the PR is not merged yet.

**Pull request closed without merging**
